language: go

go:
  - "1.13"
  - "1.14"

script: go test -bench=. -v --cover --race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - benjamin@rotational.io
      - rebecca@rotational.io
    on_success: change
    on_failure: always
